### PR TITLE
Add new ESLint exercise

### LINKED ISSUE #12: Add new ESLint exercise
I propose the addition of a new exercise as part of the ESLint challenges. This new exercise checks for new variables that refer to previously assigned variables with the ```console``` object.

### PR DESCRIPTION
**Pull request by mstaicu**
I propose the addition of a new exercise as part of the ESLint challenges. This new exercise checks for new variables that refer to previously assigned variables with the ```console``` object. fixes #12

### CODE REVIEW

**Comment by mstaicu** [comment]
Also, notice that I've left out the ```fix``` function on the reporter, because we're just notifying the user.

**Comment by mstaicu** [comment]
@kentcdodds did you get a change to check it out? I know you're pretty busy, thus I'm mentioning you here in order to bump this.

**Comment by mstaicu** [comment]
Yes, of course. I also think we should include this line:

```consoleReference.name === 'console'```

In the fixer function body, since we should only replace the ```console``` identifier, not all of them, now that we're recursively going up the references chain. What do you think?

**Comment by mstaicu** [comment]
Of course, I've must have used the template from a different test code. On it! 💪🏻

**Comment by kentcdodds** [comment]
That's fine :+1:

**Comment by mstaicu** [comment]
Ok, there we go.

**Comment by mstaicu** [comment]
No, thank you! And sorry for the hiccups along the way. 💥

**Pull request merged**
